# Generated by Django 3.0 on 2023-03-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('nme', models.CharField(max_length=60)),
                ('ag', models.IntegerField()),
            ],
        ),
    ]
