# Generated by Django 3.0 on 2023-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('nme', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=50)),
                ('ag', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
