# Generated by Django 3.0 on 2023-03-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Boot_app', '0002_auto_20230312_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='ag',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='nme',
            new_name='name',
        ),
    ]
