# Generated by Django 4.2.1 on 2023-05-16 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Boot_app', '0003_auto_20230312_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='age',
            new_name='backlog',
        ),
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
