# Generated by Django 4.2.1 on 2023-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boot_app', '0004_rename_age_register_backlog_register_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('addar', models.IntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('bacc', models.IntegerField()),
                ('bifsc', models.CharField(max_length=10)),
            ],
        ),
    ]
